[tool.poetry]
name = "jdgsim"
version = "0.1.0"
description = "dwarf galaxy N-body simulator"
authors = ["Giuseppe Viterbo"]
readme = "README.md"
packages = [{include = "jdgsim"}]

[tool.poetry.dependencies]
python = ">=3.9"
optax = ">=0.2.0"
optimistix = ">=0.0.1"
jax = ">=0.4.0"
scipy = ">=1.0.0"
astropy = ">=6.0.0"
numpy = ">=1.0.0"
equinox = ">=0.11.0"
beartype = ">=0.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
